In [2]:
import numpy as np

In [3]:
u = np.array([2,4,5,6])

In [4]:
2*u

array([ 4,  8, 10, 12])

In [15]:
v = np.array([1,0,0,2])

In [6]:
u+v

array([3, 4, 5, 8])

In [7]:
u*v

array([ 2,  0,  0, 12])

In [ ]:
u.shape[0]

Vector-Vector Multiplication

In [10]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n=u.shape[0]
    result=0.0
    for i in range(n):
        result=result+u[i]*v[i]
    return result

In [11]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [12]:
u.dot(v) #same result as previous function

np.int64(14)

Matrix-Vector Multiplication

In [8]:
b = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [16]:
b

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [22]:
def matrix_vector_multiplication(b,v):
    assert b.shape[1]==v.shape[0]
    num_rows=b.shape[0]
    result=np.zeros(num_rows)
    for i in range(num_rows):
        result[i]=vector_vector_multiplication(b[i],v)
    return result

In [23]:
matrix_vector_multiplication(b,v)

array([14.,  5.,  5.])

In [24]:
b.dot(v)

array([14,  5,  5])

Matrix-Matrix Multiplication

In [25]:
m = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0],
])

In [27]:
def matrix_matrix_multiplication(b,m):
    assert b.shape[1]==m.shape[0]
    num_rows=b.shape[0]
    num_cols=m.shape[1]
    result=np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        mi=m[:,i]
        bmi=matrix_vector_multiplication(b,mi)
        result[:,i]=bmi
    return result

In [28]:
matrix_matrix_multiplication(b,m)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [29]:
b.dot(m)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

Identity Matrix

In [11]:
I = np.eye(4)

In [12]:
b

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [13]:
b.dot(I)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

Inverse

In [21]:
k = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
])

In [23]:
ks=k[[0,1,2]]
ks

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [26]:
ks_inv=np.linalg.inv(ks)
ks_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [28]:
ks_inv.dot(ks)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])